### ISSUE TITLE
D3QN

### ISSUE THREAD

**Issue by liwenshulws** [nubot-nudt/SG-DQN#3]
Hello, I would like to ask where your code uses D3QN. I was confused when I saw TD3 in the train.py code, and would like to ask you what happened?Additionally, I am also confused about the use of dueling dqn in the paper.

**Comment by luoxi50** [comment]
@liwenshulws I have the same question. And have you run successfully?

**Comment by baixiaoer123** [comment]
成功了

**Comment by baixiaoer123** [comment]
无法复现啊，环境什么都配好了

**Comment by baixiaoer123** [comment]
2024-04-17 22:08:47, INFO: Skip_connection: True
2024-04-17 22:08:47, INFO: Number of layers: 1
2024-04-17 22:08:47, INFO: Similarity_func: concatenation
2024-04-17 22:08:47, INFO: Layerwise_graph: False
2024-04-17 22:08:47, INFO: Skip_connection: True
2024-04-17 22:08:47, INFO: Number of layers: 1
2024-04-17 22:08:47, INFO: TD3 action_dim is : 2
Traceback (most recent call last):
  File "F:\SG-D3QN\crowd_nav\test.py", line 205, in <module>
    main(sys_args)
  File "F:\SG-D3QN\crowd_nav\test.py", line 73, in main
    policy.load_model(model_weights)
  File "F:\SG-D3QN\crowd_nav\policy\TD3_rl.py", line 139, in load_model
    checkpoint = torch.load(file)
  File "D:\Anaconda\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Anaconda\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Anaconda\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/output1/best_val.pth'

**Comment by baixiaoer123** [comment]
2024-04-17 22:11:01, INFO: Using device: cpu
2024-04-17 22:11:01, INFO: Loaded RL weights with best VAL
Traceback (most recent call last):
  File "F:\SG-D3QN\crowd_nav\test.py", line 205, in <module>
    main(sys_args)
  File "F:\SG-D3QN\crowd_nav\test.py", line 51, in main
    spec.loader.exec_module(config)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'data/tsrl10rot/1/config.py'

**Comment by zhouzhiqian** [comment]
Maybe there is a mistake in the repository. TD3.py is useless in this repository, which is built for our another work. Besides, dueling architecture is in the DQN file.

**Comment by zhouzhiqian** [comment]
> 2024-04-17 22:11:01, INFO: Using device: cpu 2024-04-17 22:11:01, INFO: Loaded RL weights with best VAL Traceback (most recent call last): File "F:\SG-D3QN\crowd_nav\test.py", line 205, in main(sys_args) File "F:\SG-D3QN\crowd_nav\test.py", line 51, in main spec.loader.exec_module(config) File "", line 846, in exec_module File "", line 982, in get_code File "", line 1039, in get_data FileNotFoundError: [Errno 2] No such file or directory: 'data/tsrl10rot/1/config.py'

The solution is to set your configuration properly. The path tsrl10rot, which is created in my computer, does not exist in your computer.

**Comment by zhouzhiqian** [comment]
> @liwenshulws I have the same question. And have you run successfully?

Any other question?
